### PR TITLE
Separate expression signature `Upper` to `Upper` and `UpperUTF8`

### PR DESCRIPTION
**Pull request by wangwangwar**
Would be used by https://github.com/pingcap/tidb/pull/14124 and https://github.com/tikv/tikv/pull/6280

Signed-off-by: wangwangwar <wangwangwar@gmail.com>

### CODE REVIEW

**Comment by niedhui** [comment]
Please resolve the conflicts @wangwangwar

**Comment by breeswish** [comment]
Sorry for that, please resolve conflicts again.. :)

**Comment by wangwangwar** [comment]
@breeswish @niedhui Sorry, conflicts resolved:)

**Comment by breeswish** [comment]
Thanks!

**Pull request merged**
