### PR TITLE
tipb: support cast as year sig

### PR DESCRIPTION
**Pull request by spongedu**
Support `cast as year` sig.  This is for https://github.com/pingcap/tidb/pull/9251

### CODE REVIEW

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
@spongedu Please resolve conflicts.

**Comment by spongedu** [comment]
ok. PTAL @zz-jason

**Comment by zz-jason** [comment]
I'm going to close this PR since it's haven't been updated for a long time. Feel free to reopen it once you wish to advance this PR in the future.

**Pull request closed without merging**
