### PR TITLE
Add elems into FieldType

### PR DESCRIPTION
**Pull request by Xuanwo**

### CODE REVIEW

**Comment by Xuanwo** [comment]
The previous change is for testing CI, please ignore.

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Comment by dyzsr** [comment]
@Xuanwo can you resolve the conflicts?

**Comment by Xuanwo** [comment]
OK

**Comment by Xuanwo** [comment]
Fixed

**Comment by dyzsr** [comment]
Thanks

**Comment by Xuanwo** [comment]
So we got to merge this PR?

**Comment by windtalker** [comment]
I think we can close is pr since #217 did the same thing, and has been merged.

**Comment by Xuanwo** [comment]
I had to close my PR after someone else repeated my work.

Did I do something wrong? I don't think so.

This PR was created in February and the conflict was handled 22 days ago with the review request, but a PR created 17 days ago has already been reviewed and merged.

If there were no plans to merge my PR, please let me know in advance. I sincerely hope this doesn't happen again.

**Pull request closed without merging**
