### PR TITLE
add definition for greatest,least,round, rename righshift to rightshift

### PR DESCRIPTION
**Pull request by XuHuaiyu**
I add definition for functions Greatest, Least, Round for supporting pushing them down,
and rename RighShift to RightShift in this PR.

PTAL @shenli @hanfei1991 @coocood @tiancaiamao @zimulala

### CODE REVIEW

**Comment by shenli** [comment]
@XuHuaiyu You should update proto file and regenerate .go file.

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
@BusyJay PTAL

**Comment by BusyJay** [comment]
LGTM

**Pull request merged**
