### PR TITLE
Add function signatures for separation of arithmetic functions

### PR DESCRIPTION
**Pull request by Tjianke**
Please refer to [tidb issue 13979](https://github.com/pingcap/tidb/issues/13979) and [tidb issue 13976](https://github.com/pingcap/tidb/issues/13976) for details

### CODE REVIEW

**Comment by Tjianke** [comment]
@breeswish PTAL, thanks, I'm working separating remaining arithmetic func sigs

**Review by breeswish — APPROVED** [review]
Well done!

**Comment by breeswish** [comment]
@ichn-hu PTAL

**Comment by Tjianke** [comment]
@breeswish It seems that you need to sign CLA as well

**Pull request merged**
