### PR TITLE
tidb: Add new Sig for greatestdate/leastdate function

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Add new signature for tidb builtin comparison functions: greatestdate/leastdate

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### CODE REVIEW

**Review by windtalker — APPROVED** [review]
LGTM

**Comment by yibin87** [comment]
\run-unit-test

**Comment by yibin87** [comment]
\run-unit-tests

**Pull request merged**
