### PR TITLE
add checksum rewrite rule (#138)

### PR DESCRIPTION
**Pull request by NingLin-P**
cherry-pick #138

### CODE REVIEW

**Comment by NingLin-P** [comment]
> Wrong base branch? Where should this be cherry-picked to?

Yes, I change base branch to release-3.1.

**Comment by kennytm** [comment]
Please clean up the commits used in this PR. Perhaps do a hard reset, cherry-pick again, and force push.

**Comment by NingLin-P** [comment]
> Please clean up the commits used in this PR. Perhaps do a hard reset, cherry-pick again, and force push.

Thank! PTAL

**Comment by NingLin-P** [comment]
> Only `proto/checksum.proto`, `protobuf/checksum.rs` and `go-tipb/checksum.pb.go` should need to be changed 🤔

Because dependency problem, we have to `git revert fe02cdb` which introduce extra change.

**Comment by kennytm** [comment]
What dependency problems?

**Comment by NingLin-P** [comment]
Done. PTAL @overvenus @kennytm

**Comment by overvenus** [comment]
Look like we have to run `cargo build --features gen` to update checksum.rs

**Comment by kennytm** [comment]
Then we may need to cherry-pick #132 and #133 as well.

**Comment by overvenus** [comment]
@kennytm tikv 3.1 depends on 833c2ffd2fe7aad5224dd7c2b05fb24bc109e969 and this commit does not include protobuf changes, so I think just reverting fe02cdb is fine.

**Comment by NingLin-P** [comment]
change to reverting fe02cdb . PTAL @overvenus @kennytm

**Pull request merged**
