### PR TITLE
binlog: using stream to optimize gRPC interface of cistern

### PR DESCRIPTION
**Pull request by iamxy**
@GregoryIan @tiancaiamao PTAL

### CODE REVIEW

**Comment by GregoryIan** [comment]
I guess u forgot to submit the cistern.proto.

**Comment by iamxy** [comment]
my fault
and add a new method of cistern for dumping all history DDL jobs.

**Comment by GregoryIan** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
