### PR TITLE
src: generate rust code for more aggregation functions

### PR DESCRIPTION
**Pull request by spongedu**
Update rust proto files for support more aggregation functions. See #65  for proto/go modifications

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by breeswish** [comment]
Where is the change of the protobuf file?

**Comment by coocood** [comment]
@breeswish 
https://github.com/pingcap/tipb/pull/65

**Comment by breeswish** [comment]
@coocood Wired. I looked at the PR your referenced, and found out that it contains changes that reverted my another PR. See https://github.com/pingcap/tipb/pull/66  Are there anything that I missed?

**Comment by coocood** [comment]
@breeswish @spongedu 
Well, there is a conflict between the two PRs.
I think we can close this one.

**Comment by breeswish** [comment]
@coocood I think we need to set a repeatable environment so that every one will generate exactly the same file for the same protobuf source file. According to PR #66 and PR #65 it seems that current steps in README cannot provide such promises.

**Pull request closed without merging**
