### PR TITLE
*:init dag for rust 

### PR DESCRIPTION
**Pull request by AndreMouche**
@BusyJay  @hhkbp2 PTAL

### CODE REVIEW

**Comment by hhkbp2** [comment]
LGTM

**Comment by siddontang** [comment]
please upgrade your rust protocol version

**Comment by siddontang** [comment]
where is the protocol file ?

**Comment by AndreMouche** [comment]
https://github.com/pingcap/tipb/blob/master/proto/executor.proto @siddontang

**Pull request merged**
