### PR TITLE
Rename string functions implying UTF8 to `{fn}UTF8`

### PR DESCRIPTION
**Pull request by andylokandy**
Signed-off-by: andylokandy <andylokandy@hotmail.com>

Some string functions have confusing names, for example, `left` who should treat the arg as a valid UTF8 str while `length` should treat its arg as byte slice. 

They all have a common naming pattern that all of the functions implying UTF8 argument have a cofunctnion named to `{fn}Binary`. This pattern is confusing to contributors and is not documented anywhere. 

This PR renamed all of those `{fnBinary}` to `{fn}` just like all the other common string functions. who manipulate their argument as byte slice; it also renamed all of the `{fn}` to a `{fn}Binary` buddy to `{fn}UTF8`.

### CODE REVIEW

**Comment by breeswish** [comment]
Prefer to keep the Binary suffix otherwise you are likely to miss some rename in TiDB side (because the new name is the same to old name but they are different signatures)

**Comment by andylokandy** [comment]
I will apply the rename in TiDB with a tipb version bump.

**Comment by breeswish** [comment]
However you cannot prove that you have not missed renaming, right? Since the old one and the new one shares the same name in the same type. Compiler doesn't know they are different things even if you forget to change it.

**Comment by andylokandy** [comment]
It's quite easy to find them all by giving the original `{fn}` a different name (.e.g `LeftFoo`) in the local tipb replica. After that, I can start renaming the rest.

**Comment by andylokandy** [comment]
I think I may make the renaming PR in `tidb` before merging this one.

**Comment by breeswish** [comment]
@andylokandy I simply trust compiler more, since missing symbols will always be discovered, while manually replacing these symbols are much less convictive.

**Comment by breeswish** [comment]
LGTM. Remember to do the same thing to TiKV as well.

**Pull request merged**
