### PR TITLE
support projection and stream aggregation.

### PR DESCRIPTION
**Pull request by hanfei1991**

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by hanfei1991** [comment]
@shenli

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
Why so many changes in go file?

**Comment by hanfei1991** [comment]
@shenli I also don't know. I just executed the make.

**Comment by hanfei1991** [comment]
@shenli My protoc's version is 2.6.1

**Pull request merged**
