### PR TITLE
Rename RandWithSeed to RandWithSeedColumnRef

### PR DESCRIPTION
**Pull request by andylokandy**
Signed-off-by: andylokandy <andylokandy@hotmail.com>

Rename expression function `RandWithSeed` to `RandWithSeedColumnRef` because `RandWithSeed` with constant argument can not be pushed down.

### CODE REVIEW

**Comment by breeswish** [comment]
How about calling `RandWithSeedSeqFirst`? This exposes less implementation detail.

**Comment by andylokandy** [comment]
What does the `SeqFirst` stands for?

**Comment by breeswish** [comment]
The first number in the sequence that this PRNG generates

**Comment by andylokandy** [comment]
> The first number in the sequence that this PRNG generates

So how do we indicate that this function does not apply on constant input?

**Comment by breeswish** [comment]
@andylokandy I don't think it is needed. I simply think it is more suitable to use behaviour oriented names (i.e. the name indicates what it does) instead of scenario oriented names (i.e. the name indicates where it can be used) here, since "ColumnRef" is honestly nothing related to the expression itself.

**Comment by andylokandy** [comment]
I got you. And would `RandWithSeedFirstGen` be better?

**Comment by breeswish** [comment]
@andylokandy I'm fine with that

**Pull request merged**
