### PR TITLE
Adding vitess_hash function code to tipb

### PR DESCRIPTION
**Pull request by bezmax**
### What problem does this PR solve?

Issue Number: https://github.com/pingcap/tidb/issues/20971

Problem Summary: Implementing vitess_hash function to support efficient migration between tidb <-> vitess.

### What is changed and how it works?

Proposal: https://github.com/pingcap/tidb/issues/20971

What's Changed: New builtin_misc function added implementing vitess_hash algorithm.

### Related changes

In order PRs need to be merged:
1. (This PR) https://github.com/pingcap/tipb/pull/198
2. https://github.com/pingcap/parser/pull/1089
3. https://github.com/pingcap/tidb/pull/23493

### Release note

Added vitess_hash function which implements Vitess' hashing algorithm to determine sharding key.

### CODE REVIEW

**Comment by bezmax** [comment]
Not sure how do I sign CLA for this project?

**Review by Reminiscent — COMMENTED** [review]
LGTM

**Comment by Reminiscent** [comment]
@qw4990 PTAL

**Review by bb7133 — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]
/LGTM

**Comment by zz-jason** [comment]
it's weird that no rust code is changed.

**Pull request merged**
