### PR TITLE
add has_distinct property in expression.Expr

### PR DESCRIPTION
**Pull request by TisonKun**
ref https://github.com/pingcap/tics/issues/1428

### CODE REVIEW

**Comment by TisonKun** [comment]
@hanfei1991 @BusyJay PTAL

ref https://github.com/pingcap/tidb/pull/22867 https://github.com/pingcap/tics/issues/1428

I'm unsure how to pass tidb build stage without merging this pr so that tidb knows the new schema.

**Review by hanfei1991 — COMMENTED** [review]
/LGTM

**Comment by TisonKun** [comment]
@hanfei1991 @BusyJay this pr still blocks for at least 1 approving review required, maybe our bot doesn't land on this repo. Please take action for continue the progress, thanks.

**Comment by fzhedu** [comment]
LGTM

**Pull request merged**
