### PR TITLE
support JSON_VALID function

### PR DESCRIPTION
**Pull request by Reminiscent**
To: https://github.com/pingcap/tidb/pull/12596 cherry-pick to tidb release-3.1
add a new signature ```JSONValidOthers```

### CODE REVIEW

**Comment by zz-jason** [comment]
@Reminiscent please fix ci

**Comment by kennytm** [comment]
If it's about Prost it's blocked by #139.

**Comment by nrc** [comment]
I think the version of protobuf-build and grpc-rs need to be in sync. I would try updating protobuf-build to the latest version (or cherry pick https://github.com/pingcap/tipb/pull/133). It's probably OK to also remove Prost support for this branch.

**Comment by BusyJay** [comment]
You should also generate the rust code.

**Pull request merged**
