### PR TITLE
binlog: add grpc proto files for project of tidb-binlog

### PR DESCRIPTION
**Pull request by iamxy**

### CODE REVIEW

**Comment by iamxy** [comment]
In order to avoid conflict, I have to move these proto and go files of tidb-binlog to this repo together. @GregoryIan @tiancaiamao @coocood PTAL

**Comment by GregoryIan** [comment]
lgtm

**Comment by tiancaiamao** [comment]
LGTM

**Comment by coocood** [comment]
LGTM

**Pull request merged**
