### PR TITLE
tipb: Add greatest/least signature for cmp string as date

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

What's Changed:
Add sig for two built in functions

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### CODE REVIEW

**Review by windtalker — DISMISSED** [review]
LGTM

**Comment by yibin87** [comment]
\merge

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
