### PR TITLE
proto/select.proto: cleanup SelectRequest, it's not used any more

### PR DESCRIPTION
**Pull request by tiancaiamao**
`SelectRequest` is obsolete, so it can be clean up safely.

`ExprType` in expression.proto involves many definition which TiDB depends on, it can't be remove yet.
Would  you please clean up them in TiDB? @XuHuaiyu 

PTAL  @AndreMouche  @shenli

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@AndreMouche

**Comment by XuHuaiyu** [comment]
got it

**Pull request merged**
